### ISSUE TITLE
uses sudo

### ISSUE THREAD

**Issue by shoeper** [Phill93/ansible-nextcloud#1]
Does not work on clean Debian installs.

**Comment by Phill93** [comment]
Fixed with 2fbd3f576d7eac5de9319d4f5c1db291710cf171

**Comment by Phill93** [comment]
Now Ubuntu run fails with

> fatal: [default]: FAILED! => {
>     "failed": true, 
>     "msg": "Timeout (32s) waiting for privilege escalation prompt: "
> }

**Comment by shoeper** [comment]
Does su work on Ubuntu? Setting become_method to sudo on ubuntu should fix the issue. Not sure how it can be done automaticly. The problem why I set it to su was, that it does use sudo by default even if it is not available. Furthermore I thought su would be available on Ubuntu as well. Not sure how to fix this best.

**Comment by Phill93** [comment]
Su doesn't work on Ubuntu because the root user has no password. But you can force ansible to use su with the -S parameter.

I work on a solution that works on both Debian and Ubuntu.

**Comment by Phill93** [comment]
Closed with 8fa5d2390fe342fa19bf0f75c49da8fbd2b4fe8d
