### ISSUE TITLE
custom data directory does not properly work

### ISSUE THREAD

**Issue by shoeper** [Phill93/ansible-nextcloud#2]
The reason is likely that it is not being created.

**Comment by Phill93** [comment]
Fixed with c51614d38073b7141f8bc2dc587598117edeb798

**Comment by shoeper** [comment]
I think, that commit could have another bug because I tried to add a mysql port.

**Comment by Phill93** [comment]
No Problem i will fix him

**Comment by Phill93** [comment]
Error fixed with 8fa5d2390fe342fa19bf0f75c49da8fbd2b4fe8d
